spring:
  application:
    name: edu_openapi
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부

spoonacular:
  api:
    key: 99d54e1223msh7badc889933f424p17e542jsn9d8aa4feda33
    host: spoonacular-recipe-food-nutrition-v1.p.rapidapi.com
